general {
    lock_cmd = pidof hyprlock || (hyprlock --grace 0 && sleep 0.5)      # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    inhibit_sleep = 3
}